spring:
  datasource:
    url: jdbc:mysql://saascloud-db-mysql:3306/saascloud_zipkin?characterEncoding=utf8&useSSL=false
    schema: classpath:/mysql.sql
  sleuth:
    enabled: false
  zipkin:
    locator:
      discovery:
        enabled: true

zipkin:
  collector:
    rabbitmq:
      addresses: saascloud-mq-rabbit:5672
      username: guest
      password: guest
      queue: zipkin
  storage:
    type: mysql

security:
  oauth2:
    client:
      clientId: saascloud-client-zipkin
      clientSecret: saascloudClientSecret
      access-token-uri: http://saascloud-gateway:7979/uac/oauth/token
      user-authorization-uri: http://saascloud-gateway:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://saascloud-gateway:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://saascloud-provider-uac:8000/oauth/token_key

saascloud:
  oauth2:
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt
